In [126]:
import numpy as np

In [127]:
import pandas as pd

In [128]:
df=pd.read_csv(r"C:\Users\mruna\Predictive models\titanic.csv")

In [129]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [130]:
data = df[['Survived','Pclass','Sex','Age']]
data.fillna({'Age':data['Age'].median()}, inplace=True)
data['Sex'] = data['Sex'].map({'male': 0, 'female': 1})
data.head()
data.shape

C:\Users\mruna\AppData\Local\Temp\ipykernel_24204\1858584878.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.fillna({'Age':data['Age'].median()}, inplace=True)
C:\Users\mruna\AppData\Local\Temp\ipykernel_24204\1858584878.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Sex'] = data['Sex'].map({'male': 0, 'female': 1})


(891, 4)

In [131]:
x1=data['Pclass']
x2=data['Sex']
x3=data['Age']
X=np.column_stack([x1,x2,x3]) #891*3-->3D array
Y=np.array(data['Survived'])#891-->1D array

In [132]:
X = (X - X.mean(axis=0)) / X.std(axis=0)
print(X)

[[ 0.82737724 -0.73769513 -0.56573646]
 [-1.56610693  1.35557354  0.66386103]
 [ 0.82737724  1.35557354 -0.25833709]
 ...
 [ 0.82737724  1.35557354 -0.1046374 ]
 [-1.56610693 -0.73769513 -0.25833709]
 [ 0.82737724 -0.73769513  0.20276197]]


In [170]:
import numpy as np

class LogisticRegression:

    def __init__(self, lr, iterations):
        self.lr = lr
        self.iterations = iterations
    
    def fit(self, X, Y):
        self.m, self.n = X.shape
        self.w = np.zeros((self.n,1))
        self.b = 0 
        self.Y = Y.reshape(-1,1)
        self.X = X    
    
    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))
    
    def Loss_Function(self, f, Y):
        m = len(Y)
        loss = (-1/m) * np.sum(Y * np.log(f + 1e-9) + (1 - Y) * np.log(1 - f + 1e-9))
        return loss

    def Gradient_Descent(self, X, Y):
        for i in range(self.iterations):
            z = np.dot(X, self.w) + self.b
            f = self.sigmoid(z)

            dw = (1/self.m) * np.dot(X.T, (f - Y))
            db = (1/self.m) * np.sum(f - Y)

            self.w -= self.lr * dw
            self.b -= self.lr * db

    def predict(self, X):
        return self.sigmoid(np.dot(X, self.w) + self.b)

In [171]:
model = LogisticRegression(lr=0.0001, iterations=10000)
model.fit(X, Y)
model.Gradient_Descent(model.X, model.Y)

y_pred = model.predict(X)

In [176]:
y_pred_class = (y_pred >= 0.5).astype(int)

accuracy = np.mean(y_pred_class == Y.reshape(-1,1)) * 100
print(f"Accuracy: {accuracy:.2f}%")

Accuracy: 78.90%
